org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=false
fabric.loom.disableMinecraftVerification=true

# Fabric Properties
	minecraft_version=b1.7.3
	yarn_mappings=b1.7.3+e0778a3
    mappings_version=b1.7.3+2f404bc
	loader_version=0.19.1

# Mod Properties
    mod_version=1.0.1
    maven_group=com.exiledeye
    archives_base_name=nefext
    
# Dependencies
    stapi_version=2.0.0-alpha.5.4
    gcapi_version=3.2.5
    bhcreative_version=0.4.9